version: '3.4'

services:
  pokewebapiapp:
    depends_on:
        - db
    image: ${DOCKER_REGISTRY-}pokewebapiapp
    build:
      context: .
      dockerfile: PokeWebApiApp/Dockerfile
    ports:
        - "8080:5000"
    networks:
        - default_network
  db:
    image: mysql:8.0.27
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: pokemon
        MYSQL_USER: paulo_jeff
        MYSQL_PASSWORD: 123@abc
    volumes:
        - dbdata:/var/lib/mysql
    restart: always
    networks:
        - default_network

volumes:
  dbdata:
    
networks:
  default_network:
    driver: bridge
